[package]
name = "myapp_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
myapp_lib = { path = "../myapp_lib" }
polyester = { path = "../../../polyester-rs" }
serde_json = "1.0.81"