[package]
name = "myapp_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
polyester = { path = "../../../polyester-rs/polyester" }
maud = "0.23.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
